export const STEPS = {
  DELIVERY: "DELIVERY",
  PAYMENT: "PAYMENT",
  FINISH: "FINISH",
};

export const EXPEDITIONS = {
  GO_SEND: 'GO_SEND',
  JNE: 'JNE',
  PERSONAL: 'PERSONAL',
}

export const PAYMENTS = {
  E_WALLET: 'E_WALLET',
  BANK_TRANSFER: 'BANK_TRANSFER',
  VIRTUAL_ACCOUNT: 'VIRTUAL_ACCOUNT',
}