export const STEPS = {
  DELIVERY: "DELIVERY",
  PAYMENT: "PAYMENT",
  FINISH: "FINISH",
};

export const EXPEDITIONS = {
  GO_SEND: 'GO_SEND',
  JNE: 'JNE',
  PERSONAL: 'PERSONAL',
}

export const EXPEDITIONS_FEES = {
  GO_SEND: 15000,
  JNE: 9000,
  PERSONAL: 29000,
}

export const EXPEDITION_ESTIMATES = {
  GO_SEND: 'today',
  JNE: '2 days',
  PERSONAL: '1 day',
}

export const PAYMENTS = {
  E_WALLET: 'E_WALLET',
  BANK_TRANSFER: 'BANK_TRANSFER',
  VIRTUAL_ACCOUNT: 'VIRTUAL_ACCOUNT',
}

export const PAYMENTS_BALANCE = {
  E_WALLET: 1500000,
}

export const DROPSHIPPING_FEE = 5900;